services:
  database_postgres:
    image: postgres:14
    container_name: postgres_db
    hostname: postgres_db
    env_file:
      - path: ./.environment/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - tcc_network

  drf-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drf-api
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - database_postgres
    ports:
      - "8000:8000"
    env_file:
      - path: ./.environment/.env.django
    networks:
      - tcc_network

volumes:
  postgres_data:

networks:
  tcc_network:
    driver: bridge
