# Generated by Django 5.1.7 on 2025-04-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_batchesresults_delete_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchesResults',
            new_name='BatchResult',
        ),
    ]
