# Generated by Django 5.1.7 on 2025-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Em andamento'), (2, 'Concluída')], default=0),
        ),
    ]
