# Generated by Django 5.1.7 on 2025-07-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(choices=[(4, '4 minutos'), (5, '5 minutos'), (6, '6 minutos')], default=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15),
        ),
    ]
