# Generated by Django 5.1.7 on 2025-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_session_duration_alter_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchresult',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='player',
            name='player_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
