# Generated by Django 5.1.7 on 2025-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_result_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (20, '20 minutos')], default=2),
        ),
    ]
