# Generated by Django 5.1.7 on 2025-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
